server:
  port: 8080
  debug: true
  max_request_size: 10485760 # 10MB

database:
  host: 127.0.0.1
  port: 5432
  username: test_user
  password: test123
  database: edr_db
  ssl_mode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  database: 0

sigma:
  rules_path: "rules/"
  reload_interval: 300s # 5 minutes
  max_rules: 1000

detection:
  process_tree_depth: 10
  alert_threshold: 5
  processing_workers: 4
  retention_days: 30
